/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/webspaceship.glb -o src/Webspaceship.jsx 
*/

import React, { useRef, useEffect, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import { mergeGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js'

export default function Webspaceship({ gameOver = false, ...props }) {
  const { nodes, materials } = useGLTF('/webspaceship.glb')

  const shipGroupRef = useRef()
  const shipMeshGroupRef = useRef()
  const flame1Ref = useRef()
  const flame2Ref = useRef()
  
  const outerMat1 = useRef()
  const innerMat1 = useRef()
  const outerMat2 = useRef()
  const innerMat2 = useRef()

  // Track keyboard inputs
  const keys = useRef({
    w: false,
    a: false,
    s: false,
    d: false,
    arrowup: false,
    arrowdown: false,
    arrowleft: false,
    arrowright: false
  })
  const targetPosition = useRef(new THREE.Vector3(0, 0, 0))
  const worldShipPos = useRef(new THREE.Vector3())
  const shipBounds = useRef(new THREE.Box3())
  const shipSphere = useRef(new THREE.Sphere())

  // Color constants for lerping
  const colors = useMemo(() => {
    return {
      defaultOuter: new THREE.Color("#ff5500"),
      boostOuter: new THREE.Color("#00aaff"), // Blue fire
      defaultInner: new THREE.Color("#ffdd00"),
      boostInner: new THREE.Color("#e0f7fa") // White-blue core
    }
  }, [])

  const shipMergedGeometry = useMemo(() => {
    if (!nodes.Cube002) return null;
    const geoms = [
      nodes.Cube002.geometry.clone(),
      nodes.Cube002_1.geometry.clone(),
      nodes.Cube002_2.geometry.clone(),
      nodes.Cube002_3.geometry.clone()
    ];
    const merged = mergeGeometries(geoms);
    merged.computeBoundsTree();
    return merged;
  }, [nodes]);

  useEffect(() => {
    const handleKeyDown = (e) => {
      if (gameOver) return
      const key = e.key.toLowerCase()
      if (keys.current.hasOwnProperty(key)) keys.current[key] = true
      if (key === 'shift') window.spaceshipShift = true
    }
    const handleKeyUp = (e) => {
      const key = e.key.toLowerCase()
      if (keys.current.hasOwnProperty(key)) keys.current[key] = false
      if (key === 'shift') window.spaceshipShift = false
    }
    window.addEventListener('keydown', handleKeyDown)
    window.addEventListener('keyup', handleKeyUp)
    return () => {
      window.removeEventListener('keydown', handleKeyDown)
      window.removeEventListener('keyup', handleKeyUp)
    }
  }, [gameOver])

  useEffect(() => {
    if (!gameOver) return
    keys.current = {
      w: false,
      a: false,
      s: false,
      d: false,
      arrowup: false,
      arrowdown: false,
      arrowleft: false,
      arrowright: false
    }
    window.spaceshipShift = false
    window.spaceshipMoving = false
  }, [gameOver])

  useEffect(() => {
    // Force the outline materials to be pure black and unlit
    Object.values(materials).forEach((mat) => {
      if (mat.name === 'Material.001' || mat.name === 'Material.002') {
        mat.color.set('#000000')
        mat.emissive.set('#000000')
        mat.roughness = 1.0
        mat.metalness = 0.0
        mat.needsUpdate = true
      }
    })
  }, [materials])

  useFrame((state, delta) => {
    if (gameOver) return
    const boost = window.spaceshipBoost || 0;

    // Track active movement globally for the camera controller
    let moveUp = keys.current.w || keys.current.arrowup
    let moveDown = keys.current.s || keys.current.arrowdown
    let moveLeft = keys.current.a || keys.current.arrowleft
    let moveRight = keys.current.d || keys.current.arrowright
    
    if (window.controlMode === 'mobile') {
      if (typeof window.gyroPitch !== 'undefined' && typeof window.gyroRoll !== 'undefined') {
        const pitch = window.gyroPitch; // beta: front/back tilt [-180, 180]
        const roll = window.gyroRoll;   // gamma: left/right tilt [-90, 90]
        
        const neutralPitch = window.gyroNeutralPitch || 45;
        const neutralRoll = window.gyroNeutralRoll || 0;
        
        // Use a 15-degree deadzone around the calibrated neutral position
        if (pitch < neutralPitch - 15) moveUp = true;
        if (pitch > neutralPitch + 15) moveDown = true;
        if (roll < neutralRoll - 15) moveLeft = true;
        if (roll > neutralRoll + 15) moveRight = true;
      }
    }

    window.spaceshipMoving = moveUp || moveDown || moveLeft || moveRight;

    // Update movement target based on keys - Boost increases glide speed
    const speed = (6 + boost * 10) * delta; // Increased base and boost speed to traverse large space
    const maxOffset = 100.0; // Effectively removed boundaries so you can go as far left/right as needed

    if (moveUp && targetPosition.current.y < maxOffset) targetPosition.current.y += speed
    if (moveDown && targetPosition.current.y > -maxOffset) targetPosition.current.y -= speed
    
    // Fixed: A moves left (-x), D moves right (+x)
    if (moveLeft && targetPosition.current.x > -maxOffset) targetPosition.current.x -= speed
    if (moveRight && targetPosition.current.x < maxOffset) targetPosition.current.x += speed

    // Apply smooth gliding motion with lerp
    if (shipGroupRef.current) {
      shipGroupRef.current.position.x = THREE.MathUtils.lerp(shipGroupRef.current.position.x, targetPosition.current.x, 0.05)
      shipGroupRef.current.position.y = THREE.MathUtils.lerp(shipGroupRef.current.position.y, targetPosition.current.y, 0.05)
      
      // Auto-leveling Aerodynamics: 
      // Calculate realistic bank (roll) and pitch based purely on currently pressed keys
      // If no keys are pressed, target remains 0, making the vehicle perfectly glide back to straight
      let targetRollZ = 0;
      let targetPitchX = 0;
      
      if (moveLeft) targetRollZ = 0.6; // Roll banking left
      if (moveRight) targetRollZ = -0.6; // Roll banking right
      
      if (moveUp) targetPitchX = 0.4; // Pitch nose up
      if (moveDown) targetPitchX = -0.4; // Pitch nose down
      
      shipGroupRef.current.rotation.z = THREE.MathUtils.lerp(shipGroupRef.current.rotation.z, targetRollZ, 0.1)
      shipGroupRef.current.rotation.x = THREE.MathUtils.lerp(shipGroupRef.current.rotation.x, targetPitchX, 0.1)
      shipGroupRef.current.updateWorldMatrix(true, false)
      shipGroupRef.current.getWorldPosition(worldShipPos.current)
      shipBounds.current.setFromObject(shipGroupRef.current)
      shipBounds.current.getBoundingSphere(shipSphere.current)
      window.spaceshipPosition = {
        x: worldShipPos.current.x,
        y: worldShipPos.current.y,
        z: worldShipPos.current.z,
      }
      window.spaceshipCollider = {
        x: shipSphere.current.center.x,
        y: shipSphere.current.center.y,
        z: shipSphere.current.center.z,
        radius: Math.max(shipSphere.current.radius * 0.36, 0.22),
      }
      if (shipMeshGroupRef.current) {
        shipMeshGroupRef.current.updateWorldMatrix(true, false);
        window.spaceshipMatrixWorld = shipMeshGroupRef.current.matrixWorld;
        window.spaceshipGeometry = shipMergedGeometry;
      }
    }

    // Lerp colors based on boost
    if (outerMat1.current) {
      outerMat1.current.color.lerpColors(colors.defaultOuter, colors.boostOuter, boost)
      outerMat2.current.color.lerpColors(colors.defaultOuter, colors.boostOuter, boost)
      innerMat1.current.color.lerpColors(colors.defaultInner, colors.boostInner, boost)
      innerMat2.current.color.lerpColors(colors.defaultInner, colors.boostInner, boost)
    }

    const time = state.clock.getElapsedTime()
    // Make the flames flicker rapidly, and significantly longer on boost
    const flicker = 1 + Math.sin(time * 60) * 0.15; // Faster flicker
    const lengthBoost = 1 + (boost * 1.5); // Up to 2.5x length

    if (flame1Ref.current) flame1Ref.current.scale.y = flicker * lengthBoost
    if (flame2Ref.current) flame2Ref.current.scale.y = flicker * lengthBoost
  })

  return (
    <group {...props} dispose={null}>
      {/* Dynamic movement wrapper */}
      <group ref={shipGroupRef}>
        {/* Flip the ship 180 degrees to face away from the camera into deep space */}
        <group rotation={[0, Math.PI, 0]}>
          {/* Ship / Cartoon Cube */}
          <group ref={shipMeshGroupRef} position={[-0.544, 0.526, 1.508]} scale={0.277}>
            <mesh geometry={nodes.Cube002.geometry} material={materials.bodyred} />
            <mesh geometry={nodes.Cube002_1.geometry} material={materials.galss} />
            <mesh geometry={nodes.Cube002_2.geometry} material={materials['Material.001']} />
            <mesh geometry={nodes.Cube002_3.geometry} material={materials['Material.002']} />

            {/* Animated Thruster Flames */}
            <group position={[0.45, -0.2, -2.2]} rotation={[-Math.PI / 2, 0, 0]}>
               <mesh ref={flame1Ref} position={[0, -0.5, 0]}>
                 <coneGeometry args={[0.2, 1.1, 8]} />
                 <meshBasicMaterial ref={outerMat1} color="#ff5500" />
                 <mesh position={[0, -0.15, 0]}>
                    <coneGeometry args={[0.11, 0.8, 8]} />
                    <meshBasicMaterial ref={innerMat1} color="#ffdd00" />
                 </mesh>
               </mesh>
            </group>
            <group position={[-0.45, -0.2, -2.2]} rotation={[-Math.PI / 2, 0, 0]}>
               <mesh ref={flame2Ref} position={[0, -0.5, 0]}>
                 <coneGeometry args={[0.2, 1.1, 8]} />
                 <meshBasicMaterial ref={outerMat2} color="#ff5500" />
                 <mesh position={[0, -0.15, 0]}>
                    <coneGeometry args={[0.11, 0.8, 8]} />
                    <meshBasicMaterial ref={innerMat2} color="#ffdd00" />
                 </mesh>
               </mesh>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/webspaceship.glb')
